[mindbridge.backend]
AI_AGENTS_URL = "http://localhost:8001"
WHISPER_SERVICE_URL = "http://localhost:9000"
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "mindbridge_db"
DB_USER = "postgres"
DB_PASSWORD = "password"